// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_WDVF4AtWAVhxa9yzr2F8bduRnYGcoI',
    appId: '1:617020267417:web:38f4776669a99f69051108',
    messagingSenderId: '617020267417',
    projectId: 'ramona-8fba5',
    authDomain: 'ramona-8fba5.firebaseapp.com',
    storageBucket: 'ramona-8fba5.appspot.com',
    measurementId: 'G-XDWSCT99ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr60N5b_vJRqtDjKnXf449ZS34tU7O6jI',
    appId: '1:617020267417:android:7061d62433ad7d77051108',
    messagingSenderId: '617020267417',
    projectId: 'ramona-8fba5',
    storageBucket: 'ramona-8fba5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYykVR8S8RAp1Iw_Tm67-h1p_M0jFQvD4',
    appId: '1:617020267417:ios:235f7cf92bbe8b8c051108',
    messagingSenderId: '617020267417',
    projectId: 'ramona-8fba5',
    storageBucket: 'ramona-8fba5.appspot.com',
    iosClientId: '617020267417-cn59p1f29t2b551oih33j4all4j4ek8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshop',
  );
}
